### ISSUE TITLE
as a user I want to change a selected entity to be a different mixin

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#101]
for example I want to change a duplicated car to a truck, etc.

https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=2754%3A46915&t=sVnYuSwUzEE8xCRT-4

technical notes:
- entities placed in a 3dstreet scene via the streetmix loader use [mixins](https://aframe.io/docs/1.3.0/core/mixins.html) to define the objects
- these mixins can be changed. a common use case is to change a car model into another vehicle model, or a tree into another type of tree, etc.
- this may already work for some objects but the mixin property is located below the fold requiring scrolling. however, some entities may have their mixins "resolved" into a gltf model URL instead of the original mixin in which case changing the mixin may not actually modify the object in realtime. This will require investigation.

**Comment by ihordubas1** [comment]
Hi @kfarr 
Where we can find names and images of models to use it? Is there some specific library for it? Or for v0 we can create mock data for it.

**Comment by kfarr** [comment]
v1 closed with https://github.com/3DStreet/3dstreet-editor/pull/125
