### ISSUE TITLE
[`3dstreet` repo] for certain segment types, randomize the placement of the entities

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#104]
(this is actually for `3dstreet` repo but I put this issue in the wrong repo sorry)

similar to the randomized placement of pedestrians, randomize the distribution of vehicles and mobility devices, 

segment types include:
- turn lanes
- thru lanes
- train, bus, LRT
- pedestrian (done!)
- bike lane
- parking

consider parallel placement in scenarios:
- wide enough sidewalk (done!)
- wide enough bike lane
- wide enough motor vehicle lane?

consider altering colors of the placed entities when possible, especially vehicles (also see https://github.com/3DStreet/3dstreet/issues/166)

**Comment by burritojustice** [comment]
to make it look "organic", maybe divide the street into segments based on the relative size/length of the objects that would be in them, and then randomly place objects within those segments.

so say we shoot for 2 buses, 3 vehicles, 4 parklets, 6 bikes per "lane" -- we'd randomly place those objects within each of those segment -- a car is placed randomly within each 1/3 of the street, a bike is randomly placed within each 1/6 of the street.

parking and travel lanes should have a mix of cars and trucks

**Comment by burritojustice** [comment]
also don't forget parklets!

**Comment by kfarr** [comment]
closed with [#245](https://github.com/3DStreet/3dstreet/pull/245)
