### ISSUE TITLE
hovered items should indicate flashing red cursor

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#113]
figma: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?t=mATC6o95p3gG02oO-0

whiteboard: 

![Image](https://user-images.githubusercontent.com/470477/214883297-8aafbf1a-c5de-4341-8feb-2b044870ddee.png)

**Comment by ihordubas1** [comment]
@kfarr 
Can you send screenshot from figma, or link to example how it should look like?

**Comment by ihordubas1** [comment]
> @kfarr Can you send screenshot from figma, or link to example how it should look like?

Can you check it, please? Thanks in advance!

**Comment by ihordubas1** [comment]
@kfarr

**Comment by kfarr** [comment]
here's the best example, except instead of a cursor on a grid with equal sized squares it would be a bounding box sized for each object, and be red
https://glitch.com/~aframe-tiny-menu

you'll notice in the native a-frame inspector selector it already has an existing way to fire a react function when hover changes:
https://user-images.githubusercontent.com/470477/222052060-ca4a45d6-3d21-4c06-bb3d-08d42a945333.mov
https://github.com/aframevr/aframe-inspector/blob/master/src/components/viewport/ViewportHUD.js
we still have this file in 3dstreet editor, but have commented it out in main.js

But in this case instead of updating text in the UI, we want to adjust the dimensions and locations of an a-frame / three.js cursor box mesh each time a new raycast event is triggered.

another example video of semi transparent selected object (and hover effect)
https://twitter.com/3dstreetapp/status/1505613148249735168

**Comment by kfarr** [comment]
Hi @ihordubas1 was the above helpful? Did you have more questions on some ways to tackle this? I can provide some more guidance

**Comment by ihordubas1** [comment]
Hi @kfarr 
Do you have ideas about where it can be done in the code? 
Or maybe there are some code examples besides the glitch? Because it doesn't work just copy code from glitch and paste in project

**Comment by ihordubas1** [comment]
@kfarr

**Comment by kfarr** [comment]
closed by 3DStreet/3dstreet-editor#140

**Comment by kfarr** [comment]
next version: https://github.com/3DStreet/3dstreet/issues/596
