### ISSUE TITLE
updating model (mixin) single select component widget to match styling

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#129]
v1 is complete https://github.com/3DStreet/3dstreet-editor/issues/101

([See writeup below for updated instructions](#issuecomment-1500409780))

~However, as a user who selects another mixin, i don't want the previous mixin of a car, truck, bus, whatever to still be visible after i've selected a new item (it is confusing). Currently if I select a sedan and I choose a truck then both sedan and truck mixins are visible. Instead I only want the most recently chosen mixin to apply, the previous mixin should be removed.~

~for example I want to change a duplicated car to a truck, etc.
https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=2933-48713&t=BexDnzknQQowWoKh-4~

~Therefore:
** the task for this ticket is to show a single-select dropdown menu of mixins for entities with only 1 mixin, instead of the current select multiple dropdown menu **~

***
~- question -- in which cases are there existing entities with multiple mixins? example might include the busway - surface material with modifications such as a green bike lane or red transit lane. Or an atlas of stencils like turn arrows or bus only lane that are made up of 2 or more mixins.~

**Comment by ihordubas1** [comment]
@kfarr 
So, you want just change type of dropdown from multiple to single, do you?

**Comment by kfarr** [comment]
Hi @ihordubas1 , close, I can explain it a bit better.

Currently, for all entities, our model dropdown is multi-select. It is adapted from the `[mixin](https://aframe.io/docs/1.4.0/core/mixins.html)` a-frame inspector widget as a given entity can have multiple `mixin`'s at any time. For example an entity could have attribute of `mixin: surface-green bike-lane` would be 2 mixins where the `bike-lane` is the main object and `surface-green` is a color modifier.

We want to change the model drop-down widget to be single select in the following scenario:
* If the selected object (entity) selected has 1 or 0 mixin values, then use a single select widget instead of multi-select. An example of such a widget is here:
https://jquense.github.io/react-widgets/docs/DropdownList/
- The list of potential values should be the same as the multi-select list and should be searchable similar to the above referenced DropdownList react widget example.

Edge case to consider:
* If a user selects an entity that has 2 or more mixins, and then clicks `x` to remove one of those mixins, and then they deselect and reselect the object, the will see a dropdown menu with the ability to only select 1 mixin. In other words they cannot restore the original 2 mixin configuration through the UI. This is OK for now, we will address this later and will consider this a known bug.

Here is a visual example:
* For an entity with 2 or more mixins, they should appear exactly the same as present: 
![image](https://user-images.githubusercontent.com/470477/230638932-eb945625-bcc6-49c4-b10c-d20ecf599bc0.png)

* For an entity with 1 or 0 mixins, they should appear using the new searchable (filterable) single-select widget:
![image](https://user-images.githubusercontent.com/470477/230639205-8d75682c-9408-4f04-ac6c-00ea8e766da9.png)

Styling:
* The widget should use this styling: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=700-7987&t=Wew0EAIF2fKHqtFq-4
* Like this:
![image](https://user-images.githubusercontent.com/470477/230660785-3c1e06f1-7032-48e2-b371-403729f7b923.png)

**Comment by kfarr** [comment]
@ihordubas1 The widget now works as expected per https://github.com/3DStreet/3dstreet-editor/pull/178 but we need styling help to finish this ticket.

Can you please style the class "select-single" to match the figma designs? I only made 1 change to make it readable https://github.com/3DStreet/3dstreet-editor/blob/master/src/style/select.styl#L3

Desired: (notice no more magnifying glass icon)
![image](https://github.com/3DStreet/3dstreet-editor/assets/470477/7d078ee5-e87a-430d-b33e-e85feb6d6ef1)

**Comment by kfarr** [comment]
close with #183
