### ISSUE TITLE
keyboard controls lost after invoking editor

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#130]
in viewer-only mode, a user can move around a scene using `w` `a` `s` `d` and `↑` `↓` `→` `←` arrow keys (https://aframe.io/docs/1.4.0/components/wasd-controls.html)

However after loading editor and then re-entering viewer mode, wasd controls are lost

to reproduce:
* you can try this https://github.3dstreet.org/ to see what wasd keys do
* and then click editor, then click viewer
* then see the wasd keys don't work anymore

**Comment by kfarr** [comment]
To help with debugging this issue, @vincentfretin shared:
> Hi, I have a similar issue with my solidjs ui actually, if I switch to inspector on, off, I can move, but if I now open a solidjs modal and close, I can't move, if I open inspector on and off I can move again, this is a weird bug I'm guessing this has something to do with focused element or maybe not but it really weird because the cursor-teleport is working properly, just not the keyboard

KF: My guess is that the inspector is adding its key bindings (you can see a list of them by pressing `h`) and not restoring key bindings that may be used by other components

**Comment by kfarr** [comment]
also you'll notice that if you go to https://aframe.glitch.me/ and open inspector and go back to scene that the keyboard controls work as expected.

so it might be worth looking at some of the more recent a-frame inspector updates.

cc @vincentfretin we are seeing this bug only on 3dstreet editor, not a-frame inspector

**Comment by vincentfretin** [comment]
I have exactly the same code as aframe inspector minus 2-3 changes, I indeed don't have the issue with just opening, closing, moving. I have the issue with the steps in my the comment https://github.com/3DStreet/3dstreet-editor/issues/130#issuecomment-1472191721

**Comment by vincentfretin** [comment]
So indeed your issue may be related to a custom code in 3dstreet if even the simple opening,closing,moving doesn't work. The issue may be different than mine.

**Comment by vincentfretin** [comment]
Ok I commented some code by trial and error to find what code could produce my issue.
It doesn't make much sense to me right now, but if I comment this line
https://github.com/aframevr/aframe-inspector/blob/aecc85bcd2dde219fc272240bf8bfcd3ebf87b03/src/lib/raycaster.js#L87
my issue is gone.

**Comment by Algorush** [comment]
> It doesn't make much sense to me right now, but if I comment this line
> my issue is gone.

I checked it also helped fix this issue on 3DStreet

**Comment by vincentfretin** [comment]
Ok good to know, so it's the same issue as mine.

**Comment by Algorush** [comment]
I think I found the reason. It's related to those pieces of code:
https://github.com/aframevr/aframe/blob/aa42fe342bd1d02145054113a2737f738897825b/src/components/wasd-controls.js#L209
https://github.com/aframevr/aframe/blob/aa42fe342bd1d02145054113a2737f738897825b/src/utils/index.js#L295

After the Editor is closed, the button 'Enter editor mode' becomes the active element  (document.activeElement). And that's why keyboard events don't fire. If I make the active document.body in the console, with `document.activeElement.blur();` for example, then the keyboard controls works again.

One possible solution is to add `document.activeElement.blur()` code at the end of the Inspector/Editor's close function, here: https://github.com/3DStreet/3dstreet-editor/blob/1790e2be26b11dc31a27275ca653358ee67ed40d/src/index.js#L298

**Comment by vincentfretin** [comment]
Ah that make sense, the `event.preventDefault();` interferes with the focus logic (so with `document.activeElement`) I guess.
I'm not sure why there is `event.preventDefault();` here and if there is really the need.

```
document.activeElement.blur();
document.body.focus();
```
can be useful to have the focus again on the body like it's done when you exit fullscreen
https://github.com/aframevr/aframe/blob/fd5dddbd91ac18f949439bf1f83c8388a393845f/src/core/scene/a-scene.js#L894-L895
but it doesn't seem needed here, when I exit the inspector with shortcut or with "Back to Scene" button (with the `preventDefault()` commented).

The real fix I think is probably to remove the listeners 
https://github.com/aframevr/aframe-inspector/blob/aecc85bcd2dde219fc272240bf8bfcd3ebf87b03/src/lib/raycaster.js#L46-L48
in the `disable` function
https://github.com/aframevr/aframe-inspector/blob/aecc85bcd2dde219fc272240bf8bfcd3ebf87b03/src/lib/raycaster.js#L131

**Comment by vincentfretin** [comment]
`event.preventDefault();` is needed otherwise we can't select an entity.

Those changes fixes the issue for me: https://github.com/aframevr/aframe-inspector/pull/683

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet-editor/pull/161
