### ISSUE TITLE
create proposed architecture for cloud storage

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#137]
I would like to use Firebase to host the "cloud" storage for 3DStreet so that users can login and store street scenes without needing to download local files. This way they can share with other people easily and post on social media.

Daria is working on designs for this, you can see a WIP example of the logged-in profile and listing of street scenes here:
https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=2738-55544&t=OyiQBb3gL1omfWIO-4

She is working next on UI for login, create account.

Ask from Zade is to create a plan!
* Create a "pseudocode" or architecture diagram or another way to represent a plan for creating basic user authentication as well as simple storage for streets by UUID.
* Essentially there'd be 2 "tables" in the database -- one for `users` and one for `scenes` and maybe a join/relation table.
* Ideally we also have a plan for which "cloud functions" we'd need to create
* I would encourage you to reference the https://github.com/firebase/firebaseui-web-react library to make this as simple as possible

You can also reference this reddit thread where I ask firebase staff about this general approach and receive positive feedback:
https://www.reddit.com/r/Firebase/comments/11dpdns/starting_with_google_auth_and_then_adding/

**Comment by ihordubas1** [comment]
Hi @kfarr 
So, I propose to prepare an example authorization code through firebase with uml diagrams, do you agree?

And could you please explain more correctly, do you want to implement only google authentication (db will store all emails) and in the future create an authentication method using email and password or do you want to combine them into one (two authentication methods)?

**Comment by kfarr** [comment]
@ihordubas1 Yes UML diagram is great. And yes you are correct that the goal is to first only handle Google Authentication, and yes the DB will store emails and/or another Unique ID provided by Google Auth. And yes also correct that in the future we would use email / password authentication but not at first.

Firebase cloud functions and other firebase specific items would probably be placed in a new private repo, however the client-side code could still live in the public / open-source `3dstreet-editor` repo.

**Comment by ihordubas1** [comment]
Hello, @kfarr 
I have developed a basic React architecture using firebase services include Authorization, Firestore, and Storage.
In the project, authorization is made with the help of a token, which we obtain from the authorization service. Each user can download the scene (only .json file extension was specially made) and then open it. Scenes are not bound to anything while the user is bound to scenes. That is, one user has several scenes. You can see this in the ER-diagram, which I made specifically for a better understanding of the data-system.
Other users cannot access scenes that are not theirs. But if you wish, we can make them available to everyone.
Therefore, you can see how the system works at the basic level in the demo. You can also look at the code repository here:
https://github.com/ihordubas1/firebase-example

![image](https://user-images.githubusercontent.com/124342939/228012973-0015b24d-35ec-40b4-bfed-1c21d7d19ff1.png)

https://user-images.githubusercontent.com/124342939/227959408-7108c2ee-b176-4bea-9c35-603e8902ecd7.mov

**Comment by kfarr** [comment]
Thanks @ihordubas1 this is an excellent start. I appreciate seeing the overview video as well as the code repo.

A couple thoughts:
1. I looked through the source code and didn't see a programmatic definition of the database models ... is this something that was created in the firebase admin manually or in a separate file not in the example repo? Or did I just not see where it was stored? (For example, ruby or django store a copy of the database tables in a models.py file like so https://docs.djangoproject.com/en/4.1/topics/db/models/#quick-example. This makes it easier to run a script to create the db tables in the future instead of manually entering them, as well as keeping track of db table migrations in the future.)
2. I don't understand the scene table, can you provide more information on this? What is the difference between `Scenes_Url` and `Url` for example?
3. For storing and retrieving the actual scene, I had imagined that the JSON for a scene would be saved in a Database as JSON-like, not Storage as a text file with a `json` extension. There are a few reasons for this: a scene should soon contain metadata that could be queried, such as "title," "tag," or "long" and "lat". A scene may be constructed / deconstructed with a series of changes to the json that would ideally be reflected on other clients close to realtime which is a built-in feature with firebase AFAIK. Of course I could be wrong about this, curious to get your feedback.
4. Scenes should be visible to all users, no scene is private. However only the user who "owns" the scene may edit or delete a scene.
5. I do think we should use Storage for image (jpeg) files in the near future. For example this is a requirement to share scenes on social media with an image preview, as well as interacting with other server-side apis such as openai for image manipulation.
6. Will vite be a new dependency or was this just used for prototyping?
7. What are the next steps? Would it make sense to do another revision or 2 in this prototype mode and then migrate it over to the 3dstreet app?

* FYI the designs are being revised based on some of the work above, I can share them early next week or sooner whenever they are done.

**Comment by ihordubas1** [comment]
Hello @kfarr 
1. Unfortunately, schemas of entity models do not exist, because, first of all, this is a NoSQL database. You can see the details at the link: https://firebase.google.com/docs/firestore/data-model.
2. I probably explained it a little incorrectly. Each user just has an array of scene_url.
3. Yes, it can be done only in realtime databases. I haven’t worked with it in a bunch with other Firebase services, but I think you can try it on a prototype. And will be happy to try.
4. Ok, it’s not a problem, try to refactor the code and show with the new functionality or just keep it in mind for the future? Which option do you like better?
5. This will be similar to the principle with scenes. That each user will have an array of objects with references to images and scenes. // user: [scene, scene]; scene = {json: json, img: string}
6. No, I don’t recommend switching to white now, even though it is a small optimization for the build, especially for the dev build. But these are serious risks to have a large number of problems. Therefore, it is better not to risk now, maybe in the future it will be a really good idea. In the example, I used it only for convenience.
7. It all depends on you, if we need to see how it will all look in reality on the prototype, we can do next to the prototype, with the public version of the scenes, and change and delete it. And I am sure that the more accurately we do it on the prototype, the more smoothly we will be able to migrate to the 3dstreet app.
8. If we continue to do prototyping, it is better to share a little later, of course, because it is possible that many things will change during the development of the prototype now.

**Comment by kfarr** [comment]
Hi Ihor thanks for the update. Here are a few replies:

>  we can do next to the prototype, with the public version of the scenes, and change and delete it. 

Yes, I agree it would make sense to update the prototype one more time with public version of the scenes, and change and delete it (change and delete can only be done by scene owner)

> Scenes should be visible to all users, no scene is private. However only the user who "owns" the scene may edit or delete a scene.
>> Ok, it’s not a problem, try to refactor the code and show with the new functionality or just keep it in mind for the future? Which option do you like better?

For now we can just have all scenes publicly visible. A later paid / premium feature may be the ability to keep scenes private, but that is not required at the moment.

For designs, here is the current state: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=2738-40479
We have tried to adhere to the simple prototype capabilities and will keep updating as we continue prototype work

**Comment by ihordubas1** [comment]
Hi @kfarr 
I added what you asked for: a public version of the scenes, as well as modifying and deleting it (only the owner of the scene can modify and delete it).
If you have any other things to suggest, I wait for it!

https://user-images.githubusercontent.com/124342939/234908226-d1da3ddb-3cda-4249-bc55-74b37ad03c1c.mov

**Comment by kfarr** [comment]
I think this is good enough for prototyping stage and now to start work on the actual implementation? @Alina-Kuntsiv @ihordubas1

**Comment by kfarr** [comment]
* finish tasks in progress
* create new ticket(s) for this
