### ISSUE TITLE
new capture and share modal

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#145]
https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=3396-50819&t=lwXjrEHTt7JR3enZ-4

this also requires changing the behavior of the camera capture button:
- when pressed it uses the new `screentock` component to generate the image capture https://github.com/3DStreet/3dstreet/issues/159#issuecomment-1495444867
- this component will create an `img` element on the page with a png matching the same size as the window
- the modal will need to make use of this img somehow
-- for example the modal may copy the contents of another img tag added dynamically when the screenshot is taken by `screentock`; Or, at the component level by adding a selector to the `screentock` component to select an existing image element or one to be created with specified properties.

![image](https://user-images.githubusercontent.com/470477/230273961-c0a33e07-cbd6-4499-bfc5-23a6f47b11ef.png)

**Comment by ihordubas1** [comment]
Hi, @kfarr!
So, it turns out that I need to make a modal window that opens on the “Capture Image As PNG” button and has just a screenshot matching the same size as the window that I can download in PNG or JPEG, right?

**Comment by kfarr** [comment]
Ok this is ready, here is the glitch project with the new `screentock` component:
https://glitch.com/edit/#!/aframe-screenshot-ideas?path=index.html%3A50%3A0

**Comment by kfarr** [comment]
@ihordubas1 I have incorporated `screentock` component into 3dstreet and made a demo of how it works in this branch: https://github.com/3DStreet/3dstreet-editor/pull/174/files

I need your help to "reactify" it and make the dialog box, etc.

**Comment by ihordubas1** [comment]
Okay, it will be done soon

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet-editor/pull/191
