### ISSUE TITLE
raycaster click (select) events do not work when left-hand panel hidden

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#15]
Issue: When the left-hand (scene graph) panel is hidden, the area formerly occupied by that panel still does not accept click events that triggers selection of objects in the scene

Instead: When the left-hand panel is hidden, clicking in the area should still select objects

Example: the right-hand panel works as expected -- when it is hidden, the area formerly beneath by the panel is clickable

In this screenshot the area in the red outline does not select objects when clicked:
![image](https://user-images.githubusercontent.com/470477/182727254-31a16036-7dc3-490d-bd54-4010e53f75a5.png)

**Comment by Algorush** [comment]
I fixed this issue in the last Pull Request

**Comment by kfarr** [comment]
merged https://github.com/3DStreet/3dstreet/issues/192
