### ISSUE TITLE
update styling for component properties "below the fold"

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#150]
see https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=815-22612&t=77vcJsUItAlwOen7-4

for properties below the gray line (underneath the core properties of model, duplicate / delete buttons, position, rotation, scale) they should appear 1 property per line as to conserve space. This includes vec3

properties above the gray line (such as model, duplicate / delete buttons, position, rotation and scale) remain the same, no change.

**Comment by ihordubas1** [comment]
Hi @kfarr!
You mean here that there it is necessary to add absolutely new fields with logic? For I cannot find vec2, vec3 and the rest fields. Maybe I don’t know where exactly it is.

**Comment by kfarr** [comment]
@ihordubas1 

> You mean here that there it is necessary to add absolutely new fields with logic?

No this is styling of existing fields, not adding new ones.

Check out the widgets here: https://github.com/3DStreet/3dstreet-editor/tree/master/src/components/widgets

vec2, vec3, etc. is mentioned a few places in the codebase: https://github.com/search?q=repo%3A3DStreet%2F3dstreet-editor%20vec3&type=code

Here is an example of the widgets used to display the attribute name and values (such as `TotalColumns` and `8`):
![image](https://user-images.githubusercontent.com/470477/233766321-4ef982c3-042b-4592-b3f4-1bcbaa645042.png)

**Comment by kfarr** [comment]
Hi @ihordubas1 I think the pull request https://github.com/3DStreet/3dstreet-editor/pull/153 is incorrect and you may have misunderstood the request. 

It is not a request to change labels to "vec3" for example. The labels and values should populate exactly the same as before. It is not a request to adjust the styling of the "above the line" only to adjust styling "below the line" such that each label/property value(s) set are on one line each to save space.

![Image](https://user-images.githubusercontent.com/470477/235375592-710f3904-7b6d-4ef2-b0be-83c4daadbf20.png)

I am re-pasting the figma link from the top of the thread for convenience:
https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=1-304&t=fjOKE7rc4Sn0FnNM-0

In the above figma file, labels and values such as "vec3" or "Zoom" are illustrative of example label / values, not to be copied literally into the code.

**Comment by kfarr** [comment]
Above I say the following:
> In the above figma file, labels and values such as "vec3" or "Zoom" are illustrative of example label / values, not to be copied literally into the code.

Yet I see the following in PR187 (screenshot here):
![image](https://github.com/3DStreet/3dstreet-editor/assets/470477/d58f1294-7dea-49a0-b6ff-b5dd775a5d50)

And these lines:
https://github.com/3DStreet/3dstreet-editor/pull/187/files#diff-f4863fb4105d375bde5ae0dd8e46db333c9f57a7d93e46a98cf02de4d73c54deR49

https://github.com/3DStreet/3dstreet-editor/pull/187/files#diff-42fe8016f5746d06b8c4165056d1afbab87515b626b4250f0d1a4378ca9e6f6bR50

@ihordubas1 are you reading what I am writing in these tickets?

**Comment by ihordubas1** [comment]
I’m sorry, I looked at the options that came out and did not notice this bug, I will fix it as soon as possible, I apologize again

**Comment by kfarr** [comment]
Thanks @ihordubas1 this update looks good. Can you also answer my review comments? Then we can merge

Here's a new vs old comparison showing the improvements
![image](https://github.com/3DStreet/3dstreet-editor/assets/470477/f7531845-a4cd-4bf4-a0ea-959fc8fcd801)

**Comment by kfarr** [comment]
closed with #187
