### ISSUE TITLE
Rotate while dragging camera view by pressing shift key

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#171]
As a user in 3D View panning the viewport using a click and drag motion, I would like to be able to press "shift" while I'm dragging the camera to change into rotation instead of pan mode. I expect the rotation movement to be centered around the cursor position.

examples of other apps that do this:
* cesium ion has identical functionality
* blender has similar functionality (but switching instead from rotate to pan upon pressing modifier key)

**Comment by Algorush** [comment]
> As a user in 3D View panning the viewport using a click and drag motion, I would like to be able to press "shift" while I'm dragging the camera to change into rotation instead of pan mode. I expect the rotation movement to be centered around the cursor position.
> 
> examples of other apps that do this:
> 
> * cesium ion has identical functionality
> * blender has similar functionality (but switching instead from rotate to pan upon pressing modifier key)

But the cursor moves across the screen, i.e. a 2D plane. And when user press Shift, the camera should rotate around the point on the scene on which the cursor is currently located, if I understand correctly? That is, here to use the raycaster and the object closest to the camera to determine the point of rotation? So far, it has not been possible to download cesium. I have a bad internet signal. I will try later today

**Comment by kfarr** [comment]
* Yes, the quick answer is it would be ideal for the camera to rotate around the cursor: specifically the point where the cursor intersects with a ground plane (a plane at y=0). This is how Cesium Ion handles it
* Another possibility is for the rotation to be centered around an imaginary point x meters forward from at the center of the viewport, instead of the intersection of the cursor and a ground plane. Blender appears to use this technique.

**Comment by kfarr** [comment]
Here are a few videos:

Video of cesium ion behavior:
https://github.com/3DStreet/3dstreet-editor/assets/470477/f185d706-9fc8-4599-b5c3-c03e709b717a

Video of Blender behavior
https://github.com/3DStreet/3dstreet-editor/assets/470477/afa0e4f3-8546-4671-a0a7-df9d32f692d0

**Comment by Algorush** [comment]
OK I understood. I found the [aframe-orbit-controls](https://www.npmjs.com/package/aframe-orbit-controls) component which can be used for this. Another question - how should the interaction with the teleport-controls component take place? 
For example, in Viewer mode there are two modes - the camera is 'above the scene' and in 'pedestrian mode'.
When the camera is above the scene, we can activate the orbit-controls component by pressing Shift. It's clear here.
But when the camera is in pedestrian mode, how to use orbit-controls here when pressing Shift? Allow the user to also lift the camera up? For example, using scrolling (I can try to do this)

**Comment by kfarr** [comment]
Hi @Algorush you have the right general idea but instead of adding something new like orbit controls, this should instead be modifying behavior of the existing [editor controls](https://github.com/3DStreet/3dstreet-editor/blob/ffb6f3d67e4ba56f8fe8b23aab83fa6db3083a8d/src/lib/EditorControls.js#L214)

Some context:
- previously the editor, just like currently in the aframe inspector, rotated by default instead of pan by default
- that changed with this ticket: https://github.com/3DStreet/3dstreet-editor/issues/48 so that now pan is is default instead of rotate

So thinking about #48 , we want to change STATE to be ROTATE when the modified key is pressed

**Comment by Algorush** [comment]
Does this functionality with switching view mode with Shift need to be in Viewer or Editor mode?

**Comment by kfarr** [comment]
Just Editor mode. It can probably be done in the EditorControls.js. Right now there is onMouseDown function that changes STATE depending on which button pressed. Perhaps there could be an additional onKeyDown function that can override STATE to be rotate instead of whatever else it would be
https://github.com/3DStreet/3dstreet-editor/blob/ffb6f3d67e4ba56f8fe8b23aab83fa6db3083a8d/src/lib/EditorControls.js#L211

a v1 could be:
- first mouse down and state = panning
- then keydown shift and then state = rotating
- if keyup shift then state = panning
- (ignore where the center of rotation is)

a v2 could add:
- first keydown shift is pressed
- then mouse down, then state = rotating
- if keyup shift then state = panning
- (ignore where the center of rotation is)

a v3 could be:
- ensure the center of rotation is a the intersection of the mouse cursor and the 2d ground plane

a v4 could be nicely polished code (linted, commented, maybe even tested) allowing to change modifier key from shift to another key easily and could be a PR back to aframe inspector

**Comment by Algorush** [comment]
Yes, I made the first and second version yesterday. It works, probably do not need to do PR yet now? Currently working on version 3

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet-editor/pull/209
Made a PR for version 2, that is, so far without defining the intersection of the raycast with the scene plane. Now it works like in Blender.
I also made a raycast version and it works. But there is a sharp change in the position of the camera when a new center of rotation of the camera is determined, and this is a bit ugly and inconvenient. I'm trying to come up with a solution that looks like in Cesium

**Comment by kfarr** [comment]
I tested the PR and it is a great start, thanks!

- For the PR, version 2, this last part is still not working: if keyup shift then state = panning
- Perhaps getting version 1 working may also help with that task as well

Getting version 1 working is higher prio than version 3. In fact this isn't bad as a starting point and then coming back to optimization of version 3 at a later date.

**Comment by Algorush** [comment]
Added commit to PR. Now versions 1 and 2 seem to work as in the description?

**Comment by kfarr** [comment]
closed with #209

**Comment by Algorush** [comment]
I removed unnecessary code, I got the idea that it could be done easier. Works as described in v1, v2
https://github.com/3DStreet/3dstreet-editor/pull/215
