### ISSUE TITLE
remove duplicate model widget in properties panel

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#172]
only 1 should be visible above, not a second one below
![image](https://user-images.githubusercontent.com/470477/236597883-2003fa22-6ff7-46a1-b3bd-e7abf84b69d2.png)

**Comment by ihordubas1** [comment]
Thanks, I’ll look into it and let you know when I start implementing it

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet-editor/pull/178
