### ISSUE TITLE
when duplicating an entity I want the original entity to stay the same, not change positions

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#186]
I think the "real" solution is a PR to fix this in the [A-Frame repo](https://github.com/aframevr/aframe/). I have posted that issue here: https://github.com/aframevr/aframe-inspector/issues/688 (confusing I posted the issue in inspector repo but I think it is actually an a-frame core issue)

I am also curious if there is an alternative / short-term solution for 3DStreet, or if it is easier to fix it in aframe and wait for that to be merged.

**Comment by kfarr** [comment]
https://github.com/c-frame/sponsorship/issues/3

**Comment by vincentfretin** [comment]
PR https://github.com/aframevr/aframe-inspector/pull/695 in aframe-inspector fixes this issue.

**Comment by vincentfretin** [comment]
The same fix in https://github.com/3DStreet/3dstreet-editor/pull/219 for your repo.
