### ISSUE TITLE
error in 3dstreet-editor.js when selecting parking lane in Editor 

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet-editor#196]
An error began to appear when selecting a parking lane in Editor mode. An error message appears:
`3dstreet-editor.js:2 TypeError: Cannot use 'in' operator to search for 'totalColumns' in column`

**Comment by kfarr** [comment]
- helpful to have the exact streetmix street URL to reproduce if possible? I am trying this one and can't seem to reproduce https://3dstreet.app/#https://streetmix.net/tomasborja21/1/university-blvd
- if reproducible in 3dstreet-editor then the next step is to reproduce in the aframe-inspector

**Comment by Algorush** [comment]
sorry for not providing the URL. At this URL (https://3dstreet.app/#https://streetmix.net/tomasborja21/1/university-blvd) in the Editor I get the same error if I select one of the white parking marking. Same error when using aframe-inspector. I will try to find out
![parking-error](https://github.com/3DStreet/3dstreet-editor/assets/32197767/2a55673c-811a-4f2c-b096-23670ad5e94f)

**Comment by kfarr** [comment]
cc @vincentfretin FYI this is another bug that we can reproduce in inspector, it appears to be related to selecting an entity using atlas component with property of type `integer` but we need to diagnose a bit more. Just FYI, I can make a ticket in inspector too if helpful.

**Comment by vincentfretin** [comment]
If you reproduce the issue on aframe-inspector code and have a simple repro, yes please create the issue. Thanks!

**Comment by Algorush** [comment]
I incorrectly pointed out the error. The selection error in the inspector occurs because I use one temporary not so good solution to update the atlas-uvs parameters of the component:
`el.setAttribute('atlas-uvs', 'column')`
That is, without specifying the value of column.
I did this because for some reason atlas-uvs loses the column value when changing the geometry:height property of entity. I will try another solution, I will also try to find the reason in the code of the atlas-uvs component

**Comment by Algorush** [comment]
so far I've found another 'solution' that allows to change 'geometry:height' and then re-set the atlas-uvs 'column' property and not throw an error in the inspector when selecting an entity. I just create a dummy property with value in atlas-uvs after updating 'geometry:height' to re-set the column value from the mixin:
```
el.setAttribute('geometry', 'height', length);
el.setAttribute('atlas-uvs', 'c', 1);
```

**Comment by kfarr** [comment]
this appears to be resolved
