### ISSUE TITLE
Create layer panel

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#2]
https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=796%3A11729

**Comment by srothst1** [comment]
The next step for our 3DStreet Editor application is to implement the layers panel. As you can see in [our Figma](https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=796%3A11729), the layers panel should look roughly as follows:
<img width="242" alt="Screen Shot 2022-06-17 at 1 33 48 PM" src="https://user-images.githubusercontent.com/39531367/174397564-c7484b71-c417-4091-972c-e6dabb063227.png">

Please note that this panel is collapsible and that each item (Folsom btwn 16th and 17th Street, etc. ) should be selectable.  Upon selection, the movement, rotation, UI should appear on the item. 

We have made various modifications to `index.html` that should help facilitate these UI changes. Here are lines 41-85 from `index.html`:
```
<a-entity id="streets" data-layer-name="Street Segments">
  <a-entity
    data-layer-name="16th St West of Harrison"
    position="-98.34 0.591 -4.17918"
    rotation="0 90 0"
    id="west_street"
    street="length: 150"
    streetmix-loader="streetmixStreetURL: https://streetmix.net/kfarr/82/16th-st-harrison-st-sf-ca; showBuildings: false;"
  ></a-entity>

  <a-entity
    data-layer-name="16th St East of Harrison"
    position="78.955 5.37 -4.17918"
    rotation="-3.63 90 0"
    id="east_street"
    street="length: 150"
    streetmix-loader="streetmixStreetURL: https://streetmix.net/kfarr/82/16th-st-harrison-st-sf-ca; showBuildings: false;"
  ></a-entity>

  <a-entity data-layer-name="16th & Harrison St Intersection" id="intersection" position="-9.620 0.591 -4.17918" intersection="dimensions: 27.5 24.384;northeastcurb: 4.572 4.572;southwestcurb: 4.572 4.572;southeastcurb: 4.572 4.572;northwestcurb: 4.572 4.572;trafficsignal: 1 1 1 1;crosswalk: 1 1 1 1"></a-entity>
</a-entity>

<a-entity id="imagery" data-layer-name="Imagery">
  <a-entity
    data-layer-name="3D Scan"
    id="cesium-ion-scan"
    position="13.248 9.680 10.140"
    rotation="-90 -3.79 0"
    loader-3dtiles="url: https://assets.cesium.com/1054529/tileset.json?v=3;
    cesiumIONToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3YTYyYTIzNS0yODg0LTRhZWQtYjYxNS1iNWNhZGZhNmY3OTgiLCJpZCI6MTcwNjEsInNjb3BlcyI6WyJhc3IiLCJnYyJdLCJpYXQiOjE1NzE1OTcxNzZ9.R8mKo-NizcmOjCN_4dQyd5xO4X655CZZMXa9B5sECyU;"
    scale="1 1 1"
  ></a-entity>

  <a-entity
    data-layer-name="Map"
    geometry="primitive: plane; width: 512; height: 512;"
    material="color: #ffffff; shader: flat; side: both; transparent: true;"
    mapbox="center: -122.415126, 37.763699; zoom: 18; 
      accessToken: pk.eyJ1IjoibWF0dHJlIiwiYSI6IjRpa3ItcWcifQ.s0AGgKi0ai23K5OJvkEFnA;
      style: mapbox://styles/mapbox/satellite-streets-v11;
      pxToWorldRatio: 4;"
    position="0 0 0"
    rotation="-90 0 0"
  ></a-entity>
</a-entity>
```

Each item in the `a-entity` object with `data-layer-name="Street Segments"` should go in a drop down folder called "Street Segments". Items in this folder should be named using their `data-layer-name`. 

Each item in the `a-entity` object with `data-layer-name="Imagery"` should go in a drop down folder called "Imagery". Items in this folder should be named using their `data-layer-name`.

**Comment by kfarr** [comment]
complete with https://github.com/3DStreet/3dstreet-editor/pull/4
