### ISSUE TITLE
Save New Scene with UUID

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#211]
New feature to save 3DStreet scene json to Firebase Firestore "scenes" collection with a unique UUID.
These changes should be added to the save / load PR in progress: https://github.com/3DStreet/3dstreet-editor/pull/202

### Firestore things
The default firebase firestore ID is not a UUID, it is something different. So we will need to make sure to provide a UUID when first saving the file. Maybe there is a library for this or it is a built-in JavaScript function.

To save a new file, such as one imported from streetmix like https://3dstreet.app#https://streetmix.net/kfarr/3/, use firestore `set` with a json document ("document-shaped data" in one comment I saw). The collection name we can use for scenes is "scenes"

#### Tasks:
- Implement functionality to save new scenes with unique UUIDs.
- Use Firestore set to save a new file, like one imported from Streetmix.
- The Firestore document format should be:
```
{
  title: "string",
  version: "v1.2.3",
  author: authorID,  // only this user is permitted to modify this file 
  data: { scene nodes }
}
```
- if successful save, then change URL hash to /#/scenes/UUID.json

#### Flowchart
```mermaid
flowchart TD
    A(New or Imported Street from streetmix or gallery) --> B
    B(User makes changes in Editor and says, 'I want to save!') --> C
    C(Click Save Button) --> D
    D{Is user logged in?} --> |Yes| E
    D --> |No|F(Account Sign In) --> E
    E(Save) --> G
    G(New UUID) --> H
    H(Save scene JSON to UUID Blob) --> I
    I(Forward URL to new scene 3dstreet.app/#/scene/UUID.json)
```

#### UI
![image](https://github.com/3DStreet/3dstreet-editor/assets/470477/89273c55-524c-4907-b3fe-64daa096cd8b)
Figma: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=5072-123257&mode=design&t=7ufkGgfZj4PYVSDP-4

**Comment by rostyslavvnahornyi** [comment]
@kfarr, Hello again)

So, it must be like this?

1. im on this scene https://3dstreet.app/#https://streetmix.net/kfarr/3/example-street
2. if save(logged in)
in firebase add the new scenes table:
{
  title: "example-street",
  version: "v1.0",
  author: kfar_uuid, 
  data: JSON blob
},
3. change url to https://3dstreet.app/#/scene/example_street.json
I understand everything correctly, right or not?)

**Comment by kfarr** [comment]
Hi @rostyslavvnahornyi yes, however a few notes:
* For title you can just hardcode to "Street Scene" for now, we will add UI for editing title later
* version: "1.0" not "v1.0"
* change the URL to https://3dstreet.app/#/scenes/[NEW-UUID-JUST-CREATED].json

does that make sense?

**Comment by kfarr** [comment]
Here is progress so far:
* I have been able to cherry pick the commit to the newly renamed feature branch here: https://github.com/3DStreet/3dstreet-editor/pull/233
* I was able to get basic saving to work using security rules added as files in this branch: https://github.com/3DStreet/3dstreet-editor/pull/233/files#diff-3ed78436373d7de4022d2202afea121b7fdc4ae60bd2b9eea07e6ffac863acf8 @rostyslavvnahornyi can you double check these rules and make modifications to them if you have a better set of rules? 
* Still To-do: create instructions on how to test locally using firebase emulator since I have not deployed firebase functions that returns .json file required to fully test this

**Comment by rostyslavvnahornyi** [comment]
Okey, its a great idea to make cherry pick to new branch.
About rules: it seems like everything is fine, especially for a start. Also I think it is necessary to make more auth rules in the future. I'll still think about it

Can you explain in more detail the third point?
thanks in advance)

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet-editor/pull/233
