### ISSUE TITLE
revert to no router on save / load PR #202

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#216]
Issue: router adds complexity and forces chunking of js files by default

Impact: this affects our deployment process as well as the ability of third-party applications on different server to access the editor via 1 js include file.

instead i suggest to remove router in PR #202 which accomplishes 2 things:
- makes the code simpler for now with fewer dependencies
- removes the behavior of chunking which restores previous ability to deploy

the definition of done for this task is 1 combined js file for the app upon npm run dist with the same js filename(s) as prior.

**Comment by rostyslavnahornyi** [comment]
Hi, you are right, so i removed full react router package and all occurrences related to it. See the last commit in "issue#169" branch

**Comment by kfarr** [comment]
reviewed working as expected in PR #202
