### ISSUE TITLE
create buttons for camera switching instead of dropdown

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#24]
Instead of a dropdown with many options for camera angle, we would like 3 options arranged in buttons like so:
![image](https://user-images.githubusercontent.com/470477/188233678-ca4f69ba-0645-42ea-a87b-bdb1b79d611e.png)

3 options should be:
3D View (currently "perspective" view)
Plan View (currently "top" orthographic view)
Cross Section (currently "front" orthographic view)

Figma link: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=1760%3A17328

**Comment by kfarr** [comment]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/470477/192937955-f451041c-588e-4137-8d2e-d0edb9a6e164.png">

2 issues:

1. font does not match design
2. Modify help text. For each:

- 3D View: "3D perspective camera with click and drag rotation"
- Plan View: "Down facing orthographic camera"
- Cross Section: "Front facing orthographic camera"

**Comment by omedvediev** [comment]
fixed
