### ISSUE TITLE
Investigation - why is bundle size is 1.52MB on `feature-firebase-save-load` branch?

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#245]
After running npm run dist:prod, the bundle is 1.52MB on `feature-firebase-save-load` branch. On master branch this is only ~800KB, so the size has roughly doubled since the changes we have made. Why is this and what can we do to reduce?

warning from console:
> WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> This can impact web performance.
> Assets: 
>   3dstreet-editor.min.js (1.52 MiB)

this might be a helpful tool:
https://www.npmjs.com/package/webpack-bundle-analyzer

**Comment by kfarr** [comment]
Here is a first pass, the 2 biggest issues seem to be google.svg (300kb+) and firebase related libraries (800kb+)
![image](https://github.com/3DStreet/3dstreet-editor/assets/470477/dd149607-9c1f-4698-9443-9c30b47d32c9)


Instead of google svg included in bundle, it should be separated like other image assets. Separate ticket here: https://github.com/3DStreet/3dstreet-editor/issues/251

Regarding firebase library bundle size, here is the most relevant comment on this issue:
https://github.com/firebase/firebase-js-sdk/issues/2241#issuecomment-683130414

Firestore, auth and storage seem to be the top 3 by size. In theory they now support "tree shaking" so that only the used functions are included in the bundle. Here are official docs for upgrading to modular:
https://firebase.google.com/docs/web/modular-upgrade

It would be helpful to understand level of effort involved in changing to modular -- is it 1 hour, 5 hours ,10 hours, etc?

**Comment by rostyslavvnahornyi** [comment]
Hi, @kfarr!
When I started investigating the current version of the feature-firebase-save-load, I encountered this message in my console 

```
(8.53 MB bundle size):
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  3dstreet-editor.min.js (8.53 MiB)
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (8.53 MiB)
      3dstreet-editor.min.js
```

In our package.json, we have `firebase ^9.23.0.` According to the information provided here: https://www.npmjs.com/package/firebase, modularity is configured by default from version ^9. Therefore, our application already utilizes modularity, and both our imports and methods are written in a modular style. I also attempted to upgrade firebase to ^10.3.0 and noticed that the bundle size didn’t change.


I suggest reducing the bundle size through optimization features such as code splitting, image optimization, webpack plugins, and more.

Please let me know your thoughts on this approach.

**Comment by kfarr** [comment]
* main should be 1.2mb, not 8.5mb, are you using the latest branch of feature-firebase-save-load?
* how can we validate that tree shaking is working correctly? Can you change a setting to not use tree shaking and verify that it is a larger file size without this feature enabled?

**Comment by rostyslavvnahornyi** [comment]
- Yes, you absolutely right, the actual bundle size is 1.23mb
- Our bundle is structured in the modular style by default, with the following details:

   Entrypoints: main (1.23 MiB)
  Our bundle on compat style:
  Entrypoints: main (1.42 MiB)

Here are the differences in bundle size (firebase) between the compat style and modular style:
Compat style:
Count: 42
Total size: 481.59 KB

Modular style:
Count: 28
Modular - Total size: 372.89 KB
So, tree shaking is working

**Comment by kfarr** [comment]
ok thanks @rostyslavvnahornyi I also tried out `--mode development` webpack option which I read does not use tree shaking and that was much larger, multiple megabytes, also suggesting that normal production mode tree shaking is working correctly. I'll close this for now and we'll open separate ticket for splitting up build via route

**Comment by kfarr** [comment]
I created a new ticket but it is a low prio for now
https://github.com/3DStreet/3dstreet/issues/591
