### ISSUE TITLE
New (viewer / editor) mode switch buttons

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#25]
- The current mode of the application (viewer vs. editor) will be displayed in the same styling as the logo text
- A new button will be present next to the logo to allow switching modes between viewer and editor

In edit mode, button to enter viewer mode:
![image](https://user-images.githubusercontent.com/470477/188234476-e2da1059-1c7c-40fc-b848-ff7f4e1022fd.png)

In viewer mode, button to enter edit mode:
![image](https://user-images.githubusercontent.com/470477/188234511-fbc44b80-904f-4260-9ce4-976dc07d4205.png)

This is pending design alternatives

**Comment by kfarr** [comment]
Already there is `toggleButtonText` that can be customized and easily placed in a button. [Change these lines in Main.js](https://github.com/3DStreet/3dstreet-editor/blob/master/src/components/Main.js#L149) to:
```
      ? 'Enter Viewer mode'
      : 'Enter Editor mode';
```

And then you can use something like this to display the text [after this line in Main.js](https://github.com/3DStreet/3dstreet-editor/blob/master/src/components/Main.js#L156):
```
          <a className="viewButton">{toggleButtonText}</a>
```

However I do not know how to style this correctly and need CSS help. Here is what it looks like right now:
![image](https://user-images.githubusercontent.com/470477/188376198-ec1e4f6b-f471-4176-9267-bfd579233b0f.png)

**Comment by kfarr** [comment]
2 issues:
- logo does not switch as designed (should show "Viewer" in viewer mode and "Editor" in editor mode, see figma)
- the text label for the button from editor vs. viewer mode should be swapped (it says switch to editor when you are already in editor mode)

screenshot of the figma design that illustrates both issues:
![image](https://user-images.githubusercontent.com/470477/192940785-6427bc69-107c-4643-ac43-132e7cdfad5e.png)

**Comment by omedvediev** [comment]
1. We have some inconsistance in figma. Please, checkout the screenshot. 
![Screenshot 2022-09-29 at 11 31 05](https://user-images.githubusercontent.com/100463121/192982070-1d20b3ff-2da7-4593-9b87-062876242658.png);
So, I left the full text version for now, awaiting your decision.

2. Fixed
