### ISSUE TITLE
save / load intersections via cloud storage not working

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#255]
To reproduce:
- load `feature-firebase-save-load` branch with dev environment credentials
- open localhost:3333/index-intersection.html
- login to 3dstreet cloud via google account by clicking on person icon in upper-right hand corner
- save scene to cloud, note the UUID upon redirect after saving
- re-open using `https://dev-3dstreet.web.app/#/scenes/UUID.json` or `http://localhost:3333/#https://dev-3dstreet.web.app/#/scenes/UUID.json`
- result: note that intersection appears red instead of using proper intersection texture, and there are 2x (duplicate) sidewalk, markings, signal, etc. entities under the intersection entity parent (see below)

Instead, the intersection should look the same as localhost version in step 2 and not contain duplicate entities.

![image](https://github.com/3DStreet/3dstreet-editor/assets/470477/a6040b21-0190-4372-b67a-a9917cb1180b)

**Comment by Algorush** [comment]
I found the reason why there are duplicate elements inside intersection element. In JSON file, the intersection element is stored along with its descendants. And when loading from json, when the intersection component is initialized, the elements inside the intersection are created again. There is a simple solution - to put the intersection component inside a-entity#intersection, not in the child entity element. And second step is not to save 'intersection' child elements in JSON. To do this, add id 'intersection' to the list of elements for which not to save descendants.
So I wanted to ask if a child element with an intersection component is necessary?

**Comment by kfarr** [comment]
Ok makes sense about the cause of duplicates. I think this would be a good candidate to use the rename function to save "intersection" to "not-intersection" (this is in json-utils?) and also I agree that we should have the intersection component one level higher (that can be done from the .html file)

**Comment by kfarr** [comment]
I also notice that saving to the cloud the json is not ignored in streets (search for `not-streets` component and look at JSON property here: https://dev-3dstreet.web.app/scenes/b020190e-29a0-453e-8ee1-bcf1ca2a6d69.json)

**Comment by Algorush** [comment]
> Ok makes sense about the cause of duplicates. I think this would be a good candidate to use the rename function to save "intersection" to "not-intersection" (this is in json-utils?) and also I agree that we should have the intersection component one level higher (that can be done from the .html file)

I can also assign an id to the child element with the intersection component, for example #intersection-parent. I think it would be better, because other child elements of a-scene have a similar structure. And don't include its children in the JSON. It's just that json-utils already has a mechanism for excluding child elements from JSON, I added it when I had the same problem with the environment

**Comment by Algorush** [comment]
> I also notice that saving to the cloud the json is not ignored in streets (search for `not-streets` component and look at JSON property here: https://dev-3dstreet.web.app/scenes/b020190e-29a0-453e-8ee1-bcf1ca2a6d69.json)

I noticed this before that the JSON parameter with the string in 'not-street' is ​​saved, but I have not yet looked at why this happens. Now I want to check

**Comment by Algorush** [comment]
> Ok makes sense about the cause of duplicates. I think this would be a good candidate to use the rename function to save "intersection" to "not-intersection" (this is in json-utils?) and also I agree that we should have the intersection component one level higher (that can be done from the .html file)

About rename 'intersection' to 'not-intersection' you mean that if user will change some objects of intersection changes will not be saved if deleting all child elements from intersection node?

**Comment by Algorush** [comment]
To fix this issue, a PR has been created in 3DStreet - https://github.com/3DStreet/3dstreet/pull/341. And PR in this repo: https://github.com/3DStreet/3dstreet-editor/issues/255

**Comment by kfarr** [comment]
closed by #271
