### ISSUE TITLE
New combined save button for png + gltf downloads

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#26]
Currently there are separate icon-only buttons for a png screenshot and gltf download.

Instead we would like 1 "save" button with "save" icon that when clicked shows 3 options:
- glTF 3D Model
- PNG Screenshot
- "x" to return

Normal state:
![image](https://user-images.githubusercontent.com/470477/188234752-89bd148a-8a4a-4135-a2e0-d7db94ede3c5.png)

Clicked state showing 2 options and "x":
![image](https://user-images.githubusercontent.com/470477/188234821-30585aec-c5c6-4b2f-aafe-d5f80e0fc4b2.png)

**Comment by kfarr** [comment]
Font incorrect 
![image](https://user-images.githubusercontent.com/470477/192940355-82c5a319-5122-4bfe-8fa0-aad17d734427.png)

**Comment by omedvediev** [comment]
fixed on branch issue#24
