### ISSUE TITLE
question: can we remove `uuid` field, use built-in firebase document id instead?

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#260]
while performing operations on firebase data on serverside using console I happened to duplicate a `scenes` document and while the DocID was a new unique value, it did not match the custom field `uuid`

Can we just get rid of `uuid` field and instead use the native document id for firebase in all of the places we use uuid?

**Comment by rostyslavvnahornyi** [comment]
Yes, we can get rid of uuid, but in tasks 247, 248 i have a solution for this problem

**Comment by kfarr** [comment]
> Yes, we can get rid of uuid, but in tasks 247, 248 i have a solution for this problem

Sorry a bit confused by this response. Are you saying that the PR for tasks 247 and 248 solves this problem? I still see references to UUID field here:
https://github.com/3DStreet/3dstreet-editor/pull/273/

**Comment by kfarr** [comment]
confirmed working in #274, will wait to close until merged

**Comment by kfarr** [comment]
closed by #274
