### ISSUE TITLE
Add a help dialog box with 2 tabs

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#27]
- repurpose the existing a-frame inspector help dialog (visible when user presses "h" key)
- keep the keyboard shortcut with slight restyling per figma link below
- add a first tab that includes new instructions for camera movement and mode switching per figma link below
- add a "?" icon to the lower-right hand corner of the editor that upon clicking will show the dialog

Help Dialog Tab 1 - Essentials:
![image](https://user-images.githubusercontent.com/470477/188235529-602554b8-046f-4567-8e6b-de4ac3bf8892.png)

Tab 2 - Keyboard shortcuts
![image](https://user-images.githubusercontent.com/470477/188235627-038782b2-9317-4416-9147-93f6e062a1d0.png)

Figma link for help dialog:
https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=1787%3A18677

"?" icon:
![image](https://user-images.githubusercontent.com/470477/188235703-8fc9c0c9-dd79-4e24-a51c-738add7f2439.png)

Figma link for "?" icon:
https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=1787%3A18366

**Comment by kfarr** [comment]
Hi @omedvediev I was able to get this to run locally now with your webpack changes from https://github.com/3DStreet/3dstreet-editor/commit/abc59249710e18e0aab7e5d95f757b76ba678b1f

However I could not successfully update the branch (sync changes from master) and I thought that might help with font issues before I do a more detailed review

Would you be able to try to bring in the latest changes from master to this branch?

**Comment by omedvediev** [comment]
Hello @kfarr! Sure! I'll merge it on Monday. Have a nice weekend!

**Comment by omedvediev** [comment]
Good morning, @kfarr! The branch is updated.

**Comment by kfarr** [comment]
Thanks for updating. This is good enough to merge. I will make request for changes in separate ticket
https://github.com/3DStreet/3dstreet-editor/pull/41
