### ISSUE TITLE
Start in plan view (top down) by default on editor

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#33]
Currently the default camera view when the editor is invoked is the perspective (3d view) camera. Instead it should be the Plan View (top-down orthographic view) by default.

**Comment by omedvediev** [comment]
implemented on branch issue#24

**Comment by kfarr** [comment]
@omedvediev I removed this from #24 branch. (https://github.com/3DStreet/3dstreet-editor/commit/194e79e485ec8fbb0d7105ceb2e526a9d30b28b5)

Maybe you could create a new branch for this?

However, there is a new issue when `orthotop` is the default: when clicking on "3D View" after seeing the default plan view, the perspective camera aspect ratio is incorrect (it is squished):
![image](https://user-images.githubusercontent.com/470477/193194018-4fbc310b-6712-4b58-93c0-5733f35f139d.png)

When the window is resized the aspect ratio is updated correctly.

**Comment by omedvediev** [comment]
Hello @kfarr! I'll check out what's going wrong and find solution for this problem.

**Comment by omedvediev** [comment]
Fixed on appropriate branch ('issue#33')

**Comment by kfarr** [comment]
merged https://github.com/3DStreet/3dstreet-editor/pull/42
