### ISSUE TITLE
Remove “VR” button in viewer unless webxr device present

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#34]
When in "viewer mode" I do not want to see the "VR" button in the lower-left hand corner unless I have a VR connected device. This works correctly on the 3dstreet core viewer but has not been copied over to this repo

**Comment by kfarr** [comment]
these lines:
https://github.com/3DStreet/3dstreet/blob/main/index.html#L40-L48

should be added to here:
https://github.com/3DStreet/3dstreet-editor/blob/master/index.html

as well as adding that component to the `a-scene` entity [like this](https://github.com/3DStreet/3dstreet/blob/main/index.html#L58)

**Comment by kfarr** [comment]
This icon in lower-right hand corner should only display on VR compatible device. Use the code mentioned above for this

![Image](https://user-images.githubusercontent.com/470477/195884223-60444268-93c0-46a9-ada2-6a1ac065d69f.png)

It's okay to have inline javascript in the index.html, or you can create a new js file for code that affects "viewer mode" that is separate from the editor react js project

**Comment by botsulazade** [comment]
Finished, on branch: issue#34. [PR](https://github.com/3DStreet/3dstreet-editor/pull/49)

**Comment by kfarr** [comment]
done with https://github.com/3DStreet/3dstreet-editor/pull/52
