### ISSUE TITLE
Thumbnail not created when user does "remix" or "save as..."

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#351]
See for backstory and first attempt fail:
https://github.com/3DStreet/3dstreet-editor/pull/345#issuecomment-1826132454

**Comment by kfarr** [comment]
Hey @Algorush can you diagnose first and write up a suggested solution before working on the fix?

**Comment by Algorush** [comment]
I suggested a solution here and did a PR because I was testing this solution myself anyway https://github.com/3DStreet/3dstreet-editor/pull/345#issuecomment-1935147745

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet-editor/pull/396
