### ISSUE TITLE
Layers panel open by default

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#36]

**Comment by kfarr** [comment]
when the editor loads the 2 top-level parent entities are collapsed in the scene graph. Instead the "Street Segments" and "imagery" entities should be expanded upon load by default

Instead of the left, it should be like the right side of this picture: 

![Image](https://user-images.githubusercontent.com/470477/192943833-071e998a-7955-4a32-a40f-7289bce79cce.png)

**Comment by kfarr** [comment]
@botsulazade please rebase #36 with master and create a PR

**Comment by botsulazade** [comment]
Done
