### ISSUE TITLE
use new STREET global for notify

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#363]
3dstreet 0.4.5 should support this
https://github.com/3DStreet/3dstreet/issues/394#issuecomment-1823343566

**Comment by Algorush** [comment]
But this task has been completed and 3DStreet already supports it. Or do you mean that 3DStreet-editor should support this too?

**Comment by kfarr** [comment]
> do you mean that 3DStreet-editor should support this too?

yes!

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet-editor/pull/386
