### ISSUE TITLE
sometimes taking screenshot results in black image

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#372]
- usually, when I close the capture modal and try clicking the camera icon again, the thumbnail is created
- could there be a form of a check -- if img is black or not existing? then try to create again?

**Comment by kfarr** [comment]
related? #351

**Comment by Algorush** [comment]
After fixing #351 I didn't see examples with this issue on my localhost. @kfarr could you provide more cases with this issue please?

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet-editor/pull/396
