### ISSUE TITLE
checkbox does not always work correctly 

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet-editor#374]
I noticed one thing with the checkbox in the right panel interface. The switch doesn't work when I click on an area outside of the small circle. But at the same time the values ​​of the input checkbox change and the `checked` class is added/removed from the parent `div.checkboxAnim`. The switching animation also works.
Here the switch `showVehicles` is set to true. The value of the label at the top (showVehicles - value:true)
![image](https://github.com/3DStreet/3dstreet/assets/32197767/d1ff6b58-8be2-485d-8c0c-ccb725ddc427)

Here the switch `showVehicles` is in false mode after I click on an area outside of the small circle. But the value of the label above does not change (showVehicles - value:true). Vihicles  are on the scene.
![image](https://github.com/3DStreet/3dstreet-editor/assets/32197767/a91c4a8f-9d21-4705-828f-14570a32faa0)

here after I pressed the circle inside the switch. Everything works as it should
![image](https://github.com/3DStreet/3dstreet/assets/32197767/65a93e60-f927-4211-80b8-d776aac9cc74)

**Comment by kfarr** [comment]
@Algorush can you check if #379 fixes the issue?
