### ISSUE TITLE
number Nan issue fix from a-frame inspector

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#389]
Vincent suggested as a comment in this PR:
https://github.com/3DStreet/3dstreet-editor/pull/383#issuecomment-1925836367

https://github.com/aframevr/aframe-inspector/commit/ea6fb76500f90ecdfcc94d648ddfca17c664735e

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet-editor/pull/394

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet-editor/pull/394
