### ISSUE TITLE
entities with `data-no-pause` should always play in editor

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#406]
issue: some components such as 3d tiles should not pause when in editor mode

proposed solution:
if an entity has empty attribute of `data-no-pause`* then ensure it is playing even while other entities are paused in editor

*this naming convention continues pattern of using `data` prefix for editor stuff, such as `data-layer-name` storing user-friendly entity display name

how to do this:
* here is where the cursor is set to "play" after the entire scene is paused upon activating inspector: https://github.com/3DStreet/3dstreet-editor/blob/master/src/index.js#L262
* here is where cursor is set to play after scene play/pause toggle (currently disabled in 3dstreet editor but visible in a-frame inspector): https://github.com/3DStreet/3dstreet-editor/blob/master/src/components/scenegraph/Toolbar.js#L325

in both cases above, search for any entities with `data-no-pause` and for each `play()`

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet-editor/pull/409

**Comment by kfarr** [comment]
This works as expected. Test as follows:

add this entity to scene:
`      <a-entity test data-no-pause></a-entity>`

component code:
```
      AFRAME.registerComponent('test', {
        init: function() {
        },
        tick: function() {
          console.log('ticking')
        }
      })
```

with this change, now you will see tick events in console log even while in editor mode
