### ISSUE TITLE
"?" icon for the help dialog

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#43]

**Comment by kfarr** [comment]
A user can show the help dialog by pressing the "h" key, however we also want a "?" icon in the lower-right hand corner

See: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=1408%3A15358

**Comment by botsulazade** [comment]
Finished, on branch: issue#43. [PR](https://github.com/3DStreet/3dstreet-editor/pull/50)

**Comment by kfarr** [comment]
merged
