### ISSUE TITLE
fix UI and other issues of Layers Panel

### ISSUE THREAD

**Issue by Algorush** [3DStreet/3dstreet-editor#431]
From discord:
(1) when panel first opened it is blank until user chooses an option
(2) incorrect scroll behavior - dropdown shouldn't scroll, should always be static at top of modal
(3) Review -- are these the layers that we need? Any missing? Any shouldn't be there? (For example we should temporarly hide markings entity types because they don't work)
Issues I discovered:
(4) The panel should hide when switching Editor->Viewer

Another not UI related issues:
- delete preview entity when closing the panel or assign an id. Now a new one is created every time the panel is opened
- I see strange duplicates of created elements inside a-scene
- determine the order of adding elements not inside the `.segment-parent-..` - to `.buildings-parent` and another elements. There is a task here on how to do this so that buildings/elements are added to the right place on the scene and inside the scene graph

**Comment by Algorush** [comment]
items 1, 2, 3 (remove Stencils for now), 4 from the list have been fixed here: https://github.com/3DStreet/3dstreet-editor/pull/432

**Comment by kfarr** [comment]
@Algorush we have now merged editor into core, so you'll need to copy over your changes from PR #432 to the `3dstreet` repo as a new PR

**Comment by kfarr** [comment]
good enough for now, i'll write another ticket someday about this for future changes
