### ISSUE TITLE
Artifacts in screenshot image for PNG save

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#44]
See this ticket for instructions how to fix, the only difference is that we should fix it in this `3dstreet-editor` repo and not the `3dstreet` repo:
https://github.com/3DStreet/3dstreet/issues/159

**Comment by botsulazade** [comment]
Finished, on branch: issue#43. https://github.com/3DStreet/3dstreet-editor/pull/50

**Comment by kfarr** [comment]
the requested changes were merged, thank you! unfortunately this did not fix core issue. needs better test case before trying to fix again.

**Comment by kfarr** [comment]
resolved with https://github.com/3DStreet/3dstreet-editor/commit/274ab869f5d77e55389c8d1cd0bca7b9717a6c10
