### ISSUE TITLE
zoom buttons

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#54]
As a user navigating a scene using the editor, sometimes it is difficult to use the "scroll" movement on my mouse or trackpad and I would prefer to have buttons that I can click to zoom in or out.

Add zoom controls in the lower-right hand corner as specific in this figma: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=2188%3A21620

![image](https://user-images.githubusercontent.com/470477/201007624-dd32e2f8-206e-46df-bf2c-cd1a26ce1207.png)

clicking + zooms in, clicking - zooms out

here is a link to where a zoom function exists in the repo
https://github.com/3DStreet/3dstreet-editor/blob/fa3dfaa125e84e29d5ea0771ff31293cb7ce8646/src/lib/EditorControls.js#L159

**Comment by kfarr** [comment]
when in plan view (top-down)
- using zoom in or out button(s) creates aspect ratio issue that builds after repeated zoom button presses: zooming in the picture becomes thinner, zooming out the picture becomes wider. This issue does not exist when using the mouse based controls.

pic of 20 presses of zoom out button:
![image](https://user-images.githubusercontent.com/470477/204711710-6e2ae972-1a92-4a0e-aa7b-509ddcb31a76.png)

pic of 20 presses of zoom in button
![image](https://user-images.githubusercontent.com/470477/204711753-120befd9-018a-45ca-9adc-e8753c898a5a.png)

**Comment by omedvediev** [comment]
Hello, @kfarr! fixed.

**Comment by kfarr** [comment]
closed with #70
