### ISSUE TITLE
fix help dialog hover states and remove ? button in viewer mode

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#55]
In editor mode:

`?` button in lower-right corner needs:
* hover state for button including change button color on hover and correct mouse pointer

`x` the help dialog needs:
* hover state for x button include change button color on hover and correct mouse pointer

In viewer mode: the `?` button should NOT be visible in viewer mode

**Comment by botsulazade** [comment]
Done

**Comment by kfarr** [comment]
thanks looks great! https://github.com/3DStreet/3dstreet-editor/pull/58
