### ISSUE TITLE
injecting editor on third-party pages does not load assets

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#6]
For example:
https://3dstreet-calleja-bogota.glitch.me/

![image](https://user-images.githubusercontent.com/470477/178211858-c2eea634-4dd3-4341-ace6-c4eea55f91d7.png)

Instead, maybe we should have svg files inline the js? Or otherwise reference the files so they will be loaded on a remote server?

**Comment by Algorush** [comment]
Yes, it will help, I can do it in my new branch. Otherwise, there should be assets files on third-party pages

**Comment by Algorush** [comment]
I added the SVG code inside the CSS. Its I the new Pull Request. But now the inspector is loading slower the first time on my local server. Until I figured out why. 
...Everything loads quickly on Netlify. 
And just now I noticed that Checkbox disabled look a little higher on Netlify. Weird

**Comment by kfarr** [comment]
Thanks for the update. I think that is related to a change I made to
index.html to add a delay of 3 seconds. It is a short term fix to allow the
3dtiles to load before inspector loads

**Comment by Algorush** [comment]
I fixed checkbox sizes in new commit

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet-editor/pull/9
