### ISSUE TITLE
camera view reset button

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#75]
Add a new button (with compass icon) to reset camera view. The function of the button in 3dstreet is to reset the camera position, rotation, and zoom to the initial state.

The reset option can also be chosen by clicking the horizontal line separator. See this design:

https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=2299%3A29681&t=D8BkOcCw5FEOYiZe-4

![image](https://user-images.githubusercontent.com/470477/204584804-0d5f7384-7a69-4ed0-b4a4-f33f74417aa7.png)

To do after zoom ticket is completed https://github.com/3DStreet/3dstreet-editor/pull/70

**Comment by kfarr** [comment]
this ticket is ready to do now that #70 is complete

**Comment by omedvediev** [comment]
Hello, @kfarr , as you've closed this task-related PR, can I suspect the task also to be closed?

**Comment by kfarr** [comment]
yes this can be closed, additional features requested in #98
