### ISSUE TITLE
regression - 3dstreet viewer controls not visible

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#86]
3dstreet viewer controls (capture and load on right-hand side of screen) do not appear in the current version of 3dstreet-editor

This is a regression as they were working as part of https://github.com/3DStreet/3dstreet-editor/pull/77

Screenshot of current (Broken) on 3dstreet.app:
![image](https://user-images.githubusercontent.com/470477/206922387-abf85406-7610-470f-8cab-c631b4427a90.png)

Screenshot of current (working) on github.3dstreet.org, after pressing "Start Editor":
![image](https://user-images.githubusercontent.com/470477/206922374-49beb1cf-1b23-478e-b944-b8a4d8bcb20b.png)

**Comment by kfarr** [comment]
questions:
- is this only on 3dstreet.app or can it be reproduced on latest of `3dstreet-editor` repo?

**Comment by omedvediev** [comment]
Hello, @kfarr, sorry, but I can't reproduce the bug on master branch. Could you, please, write the algorithm how have you discovered the issue?

**Comment by kfarr** [comment]
https://3dstreet.app/

**Comment by kfarr** [comment]
resolved with https://github.com/3DStreet/3dstreet-editor/commit/f965ebf14e9dd0f2cf64116a7d77d2960116993a
