### ISSUE TITLE
Video call with Oleks

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#90]
@omedvediev would you be available to join a call Thu 29 December 8am Pacific for 45 minutes?

3DStreet / Zade weekly
Thursday, December 29 · 8:00 – 8:45am Pacific Time
Google Meet joining info
Video call link: https://meet.google.com/ydx-jibj-jwo

**Comment by Alina-Kuntsiv** [comment]
Hi @kfarr Oleksiy will reply on this tomorrow, he is off today due to family reasons. Sorry for any inconvenience!

**Comment by kfarr** [comment]
Thank you for the call today! Alina I took notes on our doc here:
https://docs.google.com/document/d/18_VvtqQpeijgwvvW8_cDaCI_L7s5lbXtO5Kmzs9wSxY/edit

A quick summary:
- we confirmed general goals of working together and that it's ok to continue to focus your work on the React application part of the 3DStreet project
- we shared feedback for improvement on both sides, primary request from my end is increased communication about when Oleks does or does not have availability to work on tickets in a given week.
- we reviewed the refactoring changes and Oleks helped me understand UIKit
