### ISSUE TITLE
regression - viewer/editor logo overlaps in editor

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#92]

**Comment by kfarr** [comment]
viewer shows:
![image](https://user-images.githubusercontent.com/470477/210466734-4c95aeea-3b96-4ab7-afa4-3a6706103686.png)

editor shows:
![image](https://user-images.githubusercontent.com/470477/210466768-f9c70125-845d-410c-b545-c1f48b4fe69c.png)

instead:
it should only show logo of current mode of application (viewer OR editor, not viewer AND editor overlapped)

**Comment by omedvediev** [comment]
Hello, @kfarr . In progress

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet-editor/pull/96
