### ISSUE TITLE
(re-open) regression - selecting an entity sometimes "crashes" editor

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#97]
Steps to reproduce:
1) checkout repo on local machine, npm install and npm run start
2) load localhost:3333
3) click on the streetmix icon (the "s") in the right-hand side
4) in the resultant scene after loading, click on sidewalk segment
5) see editor UI disappear and see console error, copied below for convenience

> Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

> react-dom.development.js?61bb:18687 The above error occurred in the <NumberWidget> component:

**Comment by kfarr** [comment]
closed with https://github.com/3DStreet/3dstreet-editor/pull/116/files

**Comment by vincentfretin** [comment]
You should reopen this issue, https://github.com/aframevr/aframe-inspector/pull/678 is a better fix than using back a deprecated api, UNSAFE_componentWillReceiveProps will surely be removed in a future react version.

**Comment by kfarr** [comment]
@ihordubas1 please see Vincent's note above as a preferred solution, thus reopening this ticket

**Comment by kfarr** [comment]
re-closed with https://github.com/3DStreet/3dstreet-editor/pull/131
