### ISSUE TITLE
loaded streets from streetmix3d.net or json loader does not show in scene graph upon load

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#99]
to reproduce:
* visit: https://3dstreet.app/
* load a 3dstreet json scene file
* notice how the left-hand scene graph does not reflect the newly loaded scene

workaround:
* close editor, re-enter editor

**Comment by kfarr** [comment]
at some point I added custom logic to filter out displaying of entitties in scene graph depending on the presence of a component property. We should consider reverting this and instead showing all

**Comment by ihordubas1** [comment]
Hello @kfarr 
I investigated this issue and I don't have it in my local environment.
But the error message on the link that you shared in the description is the same as in #97 issue. 
Probably it was fixed when we merged this issue (#97) to master.
Can you check it again, please? Thanks in advance.

**Comment by ihordubas1** [comment]
hi @kfarr 
can you check it, please?

**Comment by Algorush** [comment]
As far as I understand, now the scene graph in the interface is updated when loaded from the URL hash from streetmix. But it doesn't get updated when loaded from a JSON file because the editor mode remains on. The simplest solution here might be to reload the inspector after loading the scene from JSON

**Comment by kfarr** [comment]
@algorush you're correct that if a scene is loaded prior to the 3dstreet-editor being invoked, upon loading the 3dstreet-editor the scene graph correctly displays the scene entities as expected.

In this case I wish to support 2 things while keeping the editor open: loading a streetmix street, loading a 3dstreet json scene. I agree one option is to close / re-open the editor, that is the present workaround.

Instead I think we can invoke the reloading of the scene graph without closing/re-opening the editor.

In /src/components/scenegraph/SceneGraph.js on line 52 I think that `    this.rebuildEntityOptions();` fires the reloading of the scenegraph entities. Also next there are some events that call `this.rebuildEntityOptions();` such as `    Events.on('entityidchange', this.rebuildEntityOptions);`.

Perhaps you could try the following, just a suggestion:
* Add another event to monitor that triggers rebuilding entity such as Events.on('sceneload', this.rebuildEntityOptions);`
* Then, in the area where we allow for loading a scene such as /lib/toolbar.js line 26 `createElementsFromJSON(...` you can fire the new event `sceneload`. I forget the specific syntax for this but there are other examples in the repo

**Comment by Algorush** [comment]
Thanks for the suggestion! I added emit `entitycreated` Event at the end of the `createElementsFromJSON` function:
`Events.emit('entitycreated', streetContainerEl)`

And it works! I still need to test and change some code, but this approach works.

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet-editor/pull/201
